#include "../src/vsdlss_m3_internal.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
typedef struct { csi a,b; double w; } edge;
static double now(void){struct timespec t;timespec_get(&t,TIME_UTC);return t.tv_sec+1e-9*t.tv_nsec;}
static vsdlss *grid3(csi side){csi n=side*side*side,maxe=3*n,e=0,x,y,z,k,col,nz=0;edge*ed=malloc((size_t)maxe*sizeof(*ed));vsdlss*A;if(!ed)return NULL;
 for(z=0;z<side;z++)for(y=0;y<side;y++)for(x=0;x<side;x++){csi v=x+side*y+side*side*z;if(x+1<side)ed[e++]=(edge){v,v+1,1.01};if(y+1<side)ed[e++]=(edge){v,v+side,.93};if(z+1<side)ed[e++]=(edge){v,v+side*side,1.07};}
 A=vsdlss_spalloc(n,n,n+e,1,0);if(!A){free(ed);return NULL;}A->p[0]=0;for(col=0;col<n;col++){double d=1;for(k=0;k<e;k++)if(ed[k].a==col||ed[k].b==col)d+=ed[k].w;for(k=0;k<e;k++)if(ed[k].b==col){A->i[nz]=ed[k].a;A->x[nz++]=-ed[k].w;}A->i[nz]=col;A->x[nz++]=d;A->p[col+1]=nz;}A->nzmax=nz;free(ed);return A;}
int main(void){vsdlss*A=grid3(10),*N=NULL,*local=NULL,*P=NULL;vsdlss_components*c=NULL;vsdlss_reduction*r=NULL;vsdlss_sn_symbolic*s=NULL;vsdlss_sn_factor*sn=NULL;vsdlss_factor*m1=NULL;vsdlss_m3_factor*m3=NULL;csi*q=NULL,*pinv=NULL,k,deg[4]={0},maxw=0;double t[7],m1f,m1s,m3f,m3s,start,*b,*x1,*x3,eta1,eta3;size_t retained,temp,panels,solve_peak;if(!A)return 1;
 b=malloc((size_t)A->n*sizeof(*b));x1=malloc((size_t)A->n*sizeof(*x1));x3=malloc((size_t)A->n*sizeof(*x3));if(!b||!x1||!x3)return 1;for(k=0;k<A->n;k++)b[k]=sin(.013*(k+1))+.2*cos(.031*(k+1));
 t[0]=now();if(vsdlss_normalize_upper(A,&N))return 1;t[1]=now();if(vsdlss_components_build_normalized(N,&c))return 1;t[2]=now();if(c->count!=1||vsdlss_component_extract_normalized(N,c,0,&local)||vsdlss_reduce(local,&r))return 1;t[3]=now();if(vsdlss_order(r->core,2,&q,&pinv))return 1;P=vsdlss_symperm(r->core,pinv,1);if(!P)return 1;t[4]=now();if(vsdlss_sn_analyze(P,&s))return 1;t[5]=now();if(vsdlss_sn_factorize(P,s,&sn))return 1;t[6]=now();
 for(k=0;k<r->count;k++){if(r->records[k].degree<=3)deg[r->records[k].degree]++;}
 for(k=0;k<s->count;k++){csi w=s->column_start[k+1]-s->column_start[k];if(w>maxw)maxw=w;}
 temp=sizeof(*s)+(size_t)(s->n+(s->n+1)+2*s->l_nnz+(s->n+1)+3*(s->count+1)+s->row_ptr[s->count]+s->update_ptr[s->count])*sizeof(csi);panels=(size_t)s->panel_offset[s->count]*sizeof(double);retained=((size_t)(sn->n+1+2*sn->l_nnz+3*(sn->count+1)+sn->row_ptr[sn->count]))*sizeof(csi)+sizeof(*sn);solve_peak=(size_t)(A->n+3*r->n+4*r->core_n+2*r->count)*sizeof(double)+(size_t)c->count*sizeof(vsdlss_status);
 start=now();if(vsdlss_factorize(A,2,&m1))return 1;m1f=now()-start;start=now();if(vsdlss_factor_solve(m1,b,x1))return 1;m1s=now()-start;start=now();if(vsdlss_factorize_m3(A,2,&m3))return 1;m3f=now()-start;start=now();if(vsdlss_m3_solve(m3,b,x3))return 1;m3s=now()-start;
 if(vsdlss_backward_error(A,x1,b,&eta1)||vsdlss_backward_error(A,x3,b,&eta3))return 1;
 printf("graph=grid3_10 n=%lld nnz=%lld components=%lld\n",(long long)A->n,(long long)A->p[A->n],(long long)c->count);printf("eliminated d0=%lld d1=%lld d2=%lld d3=%lld core_n=%lld core_nnz=%lld\n",(long long)deg[0],(long long)deg[1],(long long)deg[2],(long long)deg[3],(long long)r->core_n,(long long)r->core->p[r->core_n]);printf("supernodes=%lld max_width=%lld panel_slots=%lld panel_bytes=%zu\n",(long long)s->count,(long long)maxw,(long long)s->panel_offset[s->count],panels);printf("temporary_symbolic_update_target_slots=%lld symbolic_metadata_bytes=%zu retained_factor_metadata_bytes=%zu\n",(long long)s->update_ptr[s->count],temp,retained);printf("estimated_peak_solve_workspace_bytes=%zu (exact scoped estimate for facade solve temporaries; single component; excludes retained factor, input/output, OpenMP runtime, and allocator overhead)\n",solve_peak);printf("phase_ms normalize=%.3f components=%.3f extract_reduce=%.3f order_permute=%.3f symbolic=%.3f numeric=%.3f\n",1e3*(t[1]-t[0]),1e3*(t[2]-t[1]),1e3*(t[3]-t[2]),1e3*(t[4]-t[3]),1e3*(t[5]-t[4]),1e3*(t[6]-t[5]));printf("facade_ms m1_factor=%.3f m1_solve=%.3f m3_factor=%.3f m3_solve=%.3f\n",1e3*m1f,1e3*m1s,1e3*m3f,1e3*m3s);printf("backward_error m1=%.3e m3=%.3e\n",eta1,eta3);
 free(b);free(x1);free(x3);free(q);free(pinv);vsdlss_factor_free(m1);vsdlss_m3_factor_free(m3);vsdlss_sn_factor_free(sn);vsdlss_sn_symbolic_free(s);vsdlss_reduction_free(r);vsdlss_spfree(P);vsdlss_spfree(local);vsdlss_components_free(c);vsdlss_spfree(N);vsdlss_spfree(A);return 0;}
