/* Auto-generated weak stub implementations for the external
 * library symbols (Intel MKL/comp, CUDA, tcmalloc, ANSYS nffr,
 * OpenSSL, Tcl, zlib).  These let the reference build link without
 * the proprietary runtime.  Each is weak, so providing the real
 * library overrides the stub.  Do NOT use these for real numerics.
 */
#include "vsdlss_extern.h"

void _(void) __attribute__((weak)) {}
void _ZN7request21get(void) __attribute__((weak)) {}
void _ZNSt7__cxx1112b(void) __attribute__((weak)) {}
void _(void) __attribute__((weak)) {}
void _ZN10CAclClient1(void) __attribute__((weak)) {}
void __cxa_throw_bad_(void) __attribute__((weak)) {}
void _ZSt17__throw_ba(void) __attribute__((weak)) {}
void _ZN10CAclClient5(void) __attribute__((weak)) {}
void _ZN7request23Set(void) __attribute__((weak)) {}
void _(void) __attribute__((weak)) {}
void feof(void) __attribute__((weak)) {}
void uname(void) __attribute__((weak)) {}
void _ZNSt9bad_allocD1Ev(void) __attribute__((weak)) {}
void ffw_CreateTreeBy(void) __attribute__((weak)) {}
void __(void) __attribute__((weak)) {}
void _ZN13mfsolver64l(void) __attribute__((weak)) {}
void Tcl_FirstHashEntry(void) __attribute__((weak)) {}
void _ZN7request14Get(void) __attribute__((weak)) {}
void _Z10to_secondsNS(void) __attribute__((weak)) {}
void _ZN16CAnsFeature(void) __attribute__((weak)) {}
void __(void) __attribute__((weak)) {}
void DGESVD(void) __attribute__((weak)) {}
void _ZNSt6localeC1Ev(void) __attribute__((weak)) {}
void _ZSt18_Rb_tree_i(void) __attribute__((weak)) {}
void times(void) __attribute__((weak)) {}
void csqrt(void) __attribute__((weak)) {}
void _ZNKSt7__cxx1112(void) __attribute__((weak)) {}
void _Z17get_hostname(void) __attribute__((weak)) {}
void gzprintf(void) __attribute__((weak)) {}
void _ZN9ans_mutexD1Ev(void) __attribute__((weak)) {}
void dlartv_(void) __attribute__((weak)) {}
void _ZNSt8ios_baseC2Ev(void) __attribute__((weak)) {}
void _ZN7XMLNode11par(void) __attribute__((weak)) {}
void DGETRS(void) __attribute__((weak)) {}
void ftell(void) __attribute__((weak)) {}
void ffw_CreateVarByHandle(void) __attribute__((weak)) {}
void _ZN10CAliClient1(void) __attribute__((weak)) {}
void _ZNSt8bad_castD2Ev(void) __attribute__((weak)) {}
void _ZNSo9_M_insertI(void) __attribute__((weak)) {}
void mkdir(void) __attribute__((weak)) {}
void ffw_CreateVarVal(void) __attribute__((weak)) {}
void _ZNSt13basic_fil(void) __attribute__((weak)) {}
void DGEMM(void) __attribute__((weak)) {}
void lseek(void) __attribute__((weak)) {}
void ZGETRF(void) __attribute__((weak)) {}
void _ZStlsIcSt11char(void) __attribute__((weak)) {}
void atoi(void) __attribute__((weak)) {}
void _ZNSt9basic_iosI(void) __attribute__((weak)) {}
void _Z3nowB5cxx11b(void) __attribute__((weak)) {}
void _ZN7request14get(void) __attribute__((weak)) {}
void _ZSt9terminatev(void) __attribute__((weak)) {}
void _ZNSt13runtime_e(void) __attribute__((weak)) {}
void gzgets(void) __attribute__((weak)) {}
void fputs(void) __attribute__((weak)) {}
void _Z16set_debug_lo(void) __attribute__((weak)) {}
void _(void) __attribute__((weak)) {}
void _ZNSt8ios_baseD2Ev(void) __attribute__((weak)) {}
void _ZSt29_Rb_tree_i(void) __attribute__((weak)) {}
void __cxa_call_unexpected(void) __attribute__((weak)) {}
void _ZNKSt5ctypeIcE1(void) __attribute__((weak)) {}
void __cxa_bad_cast(void) __attribute__((weak)) {}
void vfork(void) __attribute__((weak)) {}
void rmdir(void) __attribute__((weak)) {}
void _ZStlsISt11char_(void) __attribute__((weak)) {}
void _ZN14CAnsLicCont(void) __attribute__((weak)) {}
void _ZN7request15set(void) __attribute__((weak)) {}
void tanh(void) __attribute__((weak)) {}
void _ZNSolsEs(void) __attribute__((weak)) {}
void _ZN7request9get_(void) __attribute__((weak)) {}
void ffw_BeginTree(void) __attribute__((weak)) {}
void _ZNK7XMLNode12ge(void) __attribute__((weak)) {}
void _ZN7XMLNodeD1Ev(void) __attribute__((weak)) {}
void _ZN7request7get_(void) __attribute__((weak)) {}
void gzflush(void) __attribute__((weak)) {}
void _ZStrsIcSt11char(void) __attribute__((weak)) {}
void _Z20read_anslic_(void) __attribute__((weak)) {}
void _ZNK7XMLNode7get(void) __attribute__((weak)) {}
void ffw_EndTree(void) __attribute__((weak)) {}
void _ZNSt9exceptionD2Ev(void) __attribute__((weak)) {}
void _ZNK7XMLNode7isE(void) __attribute__((weak)) {}
void creat(void) __attribute__((weak)) {}
void _ZNKSt13runtime_(void) __attribute__((weak)) {}
void ffw_CreateUpscope(void) __attribute__((weak)) {}
void _ZN19CAnsStringU(void) __attribute__((weak)) {}
void _ZN7request27Get(void) __attribute__((weak)) {}
void atan2(void) __attribute__((weak)) {}
void _ZNSs6resizeEmc(void) __attribute__((weak)) {}
void _ZN7request19Get(void) __attribute__((weak)) {}
void re(void) __attribute__((weak)) {}
void _ZN7request20Get(void) __attribute__((weak)) {}
void sqrtf(void) __attribute__((weak)) {}
void _ZSt28_Rb_tree_r(void) __attribute__((weak)) {}
void _ZN11anslic_util(void) __attribute__((weak)) {}
void compress2(void) __attribute__((weak)) {}
void _ZN10CAclClient6(void) __attribute__((weak)) {}
void cexp(void) __attribute__((weak)) {}
void _ZN15CAnsLicMess(void) __attribute__((weak)) {}
void exp(void) __attribute__((weak)) {}
void _ZSt4endlIcSt11c(void) __attribute__((weak)) {}
void bzero(void) __attribute__((weak)) {}
void _Z13get_temp_fil(void) __attribute__((weak)) {}
void utime(void) __attribute__((weak)) {}
void _ZN7request13get(void) __attribute__((weak)) {}
void __cxa_guard_acquire(void) __attribute__((weak)) {}
void _Z27expwarn_msg_(void) __attribute__((weak)) {}
void ftime(void) __attribute__((weak)) {}
void _ZN7requestC1ENS(void) __attribute__((weak)) {}
void _ZSt20__throw_le(void) __attribute__((weak)) {}
void DGEBAL(void) __attribute__((weak)) {}
void _ZNSt6localeC1ERKS_(void) __attribute__((weak)) {}
void _ZSt20__throw_ou(void) __attribute__((weak)) {}
void dcopy_(void) __attribute__((weak)) {}
void _ZN9ans_mutex6un(void) __attribute__((weak)) {}
void shmdt(void) __attribute__((weak)) {}
void DTRTRS(void) __attribute__((weak)) {}
void _ZSt24__throw_ou(void) __attribute__((weak)) {}
void _ZN7request9set_(void) __attribute__((weak)) {}
void asin(void) __attribute__((weak)) {}
void popen(void) __attribute__((weak)) {}
void _ZN9ans_mutex4lockEb(void) __attribute__((weak)) {}
void _ZN7request11get(void) __attribute__((weak)) {}
void pipe(void) __attribute__((weak)) {}
void _ZNSt15basic_str(void) __attribute__((weak)) {}
void tan(void) __attribute__((weak)) {}
void Tcl_InitHashTable(void) __attribute__((weak)) {}
void _ZNSt8ios_base4I(void) __attribute__((weak)) {}
void log(void) __attribute__((weak)) {}
void _Z16all_digit_st(void) __attribute__((weak)) {}
void fsync(void) __attribute__((weak)) {}
void _ZN7request15get(void) __attribute__((weak)) {}
void DHSEQR(void) __attribute__((weak)) {}
void _ZNSirsERi(void) __attribute__((weak)) {}
void log2(void) __attribute__((weak)) {}
void gzclose(void) __attribute__((weak)) {}
void finite(void) __attribute__((weak)) {}
void dasum_(void) __attribute__((weak)) {}
void gzwrite(void) __attribute__((weak)) {}
void _ZNSi10_M_extrac(void) __attribute__((weak)) {}
void __cxa_free_exception(void) __attribute__((weak)) {}
void _ZN7request15Get(void) __attribute__((weak)) {}
void _ZN16CAnsAcademi(void) __attribute__((weak)) {}
void _Z14reset_log_fi(void) __attribute__((weak)) {}
void _ZSt15set_new_ha(void) __attribute__((weak)) {}
void _Z27GetVersionSp(void) __attribute__((weak)) {}
void log10f(void) __attribute__((weak)) {}
void __cxa_get_except(void) __attribute__((weak)) {}
void log10(void) __attribute__((weak)) {}
void _ZN25CAnsLicCont(void) __attribute__((weak)) {}
void pow(void) __attribute__((weak)) {}
void _Z17NewAnsLicMes(void) __attribute__((weak)) {}
void dirfd(void) __attribute__((weak)) {}
void powf(void) __attribute__((weak)) {}
void umask(void) __attribute__((weak)) {}
void gzputs(void) __attribute__((weak)) {}
void __cxa_allocate_e(void) __attribute__((weak)) {}
void _(void) __attribute__((weak)) {}
void _(void) __attribute__((weak)) {}
void __cxa_throw(void) __attribute__((weak)) {}
void _ZN7request11Set(void) __attribute__((weak)) {}
void DGETRF(void) __attribute__((weak)) {}
void _Z14string_trima(void) __attribute__((weak)) {}
void _Z12prdinfo_itos(void) __attribute__((weak)) {}
void drotm_(void) __attribute__((weak)) {}
void Tcl_DeleteHashTable(void) __attribute__((weak)) {}
void _Z15ans_IntToStr(void) __attribute__((weak)) {}
void _ZN7request21set(void) __attribute__((weak)) {}
void dswap_(void) __attribute__((weak)) {}
void _Z20DeleteAnsLic(void) __attribute__((weak)) {}
void _ZNSt14basic_ofs(void) __attribute__((weak)) {}
void ZHEEV(void) __attribute__((weak)) {}
void _ZN7request7set_(void) __attribute__((weak)) {}
void dtrsv_(void) __attribute__((weak)) {}
void gzeof(void) __attribute__((weak)) {}
void DGEHRD(void) __attribute__((weak)) {}
void fseek(void) __attribute__((weak)) {}
void _Z17unset_enviro(void) __attribute__((weak)) {}
void dup(void) __attribute__((weak)) {}
void _ZN10CAclClient2(void) __attribute__((weak)) {}
void _ZSt5flushIcSt11(void) __attribute__((weak)) {}
void fopen(void) __attribute__((weak)) {}
void _ZN7request18Set(void) __attribute__((weak)) {}
void _Z29SetVersionSp(void) __attribute__((weak)) {}
void ZLANGE(void) __attribute__((weak)) {}
void cos(void) __attribute__((weak)) {}
void ZGETRS(void) __attribute__((weak)) {}
void _ZNSolsEPFRSt8io(void) __attribute__((weak)) {}
void clock(void) __attribute__((weak)) {}
void _(void) __attribute__((weak)) {}
void ffw_SetScaleUnit(void) __attribute__((weak)) {}
void __cxa_guard_abort(void) __attribute__((weak)) {}
void _Z19ans_StringTo(void) __attribute__((weak)) {}
void _ZN7request19Acl(void) __attribute__((weak)) {}
void _Z22delete_ansli(void) __attribute__((weak)) {}
void _(void) __attribute__((weak)) {}
void _Z9diff_daysNSt7(void) __attribute__((weak)) {}
void cosh(void) __attribute__((weak)) {}
void daxpy_(void) __attribute__((weak)) {}
void _ZNSs6appendEPKcm(void) __attribute__((weak)) {}
void dgeqrf_(void) __attribute__((weak)) {}
void chmod(void) __attribute__((weak)) {}
void fcntl(void) __attribute__((weak)) {}
void idamax_(void) __attribute__((weak)) {}
void ffw_CreateXCoorByHnL(void) __attribute__((weak)) {}
void _Z14SetAnsysLicD(void) __attribute__((weak)) {}
void _ZN7request20set(void) __attribute__((weak)) {}
void ZHEEVR(void) __attribute__((weak)) {}
void _Z21anslic_messa(void) __attribute__((weak)) {}
void _ZN10CAclClient3(void) __attribute__((weak)) {}
void DLAIC1(void) __attribute__((weak)) {}
void _Z15DeleteAclCli(void) __attribute__((weak)) {}
void _ZNSolsEPFRSoS_E(void) __attribute__((weak)) {}
void close(void) __attribute__((weak)) {}
void _ZNSt6localeD1Ev(void) __attribute__((weak)) {}
void _ZNSs12_M_leak_hardEv(void) __attribute__((weak)) {}
void _ZNSdD2Ev(void) __attribute__((weak)) {}
void _ZN10CAclClient7(void) __attribute__((weak)) {}
void _(void) __attribute__((weak)) {}
void _ZNSolsEi(void) __attribute__((weak)) {}
void _Z15get_ansysli_(void) __attribute__((weak)) {}
void dlasr_(void) __attribute__((weak)) {}
void _ZN7requestC1Ev(void) __attribute__((weak)) {}
void acos(void) __attribute__((weak)) {}
void _Z15ans_StringTo(void) __attribute__((weak)) {}
void _ZN7request16get(void) __attribute__((weak)) {}
void _ZN7request16Set(void) __attribute__((weak)) {}
void gzgetc(void) __attribute__((weak)) {}
void gzopen(void) __attribute__((weak)) {}
void _ZNSt16invalid_a(void) __attribute__((weak)) {}
void __cxa_begin_catch(void) __attribute__((weak)) {}
void _ZNKSt9basic_ios(void) __attribute__((weak)) {}
void getc(void) __attribute__((weak)) {}
void _Z13anslic_strin(void) __attribute__((weak)) {}
void _ZN7request8set_(void) __attribute__((weak)) {}
void ffw_Close(void) __attribute__((weak)) {}
void gzread(void) __attribute__((weak)) {}
void open(void) __attribute__((weak)) {}
void ceil(void) __attribute__((weak)) {}
void _ZNSi7getlineEPclc(void) __attribute__((weak)) {}
void dgemv_(void) __attribute__((weak)) {}
void scanf(void) __attribute__((weak)) {}
void _Z14anslic_messa(void) __attribute__((weak)) {}
void atan(void) __attribute__((weak)) {}
void _(void) __attribute__((weak)) {}
void ZHERK(void) __attribute__((weak)) {}
void _ZSt9use_facetIS(void) __attribute__((weak)) {}
void _ZNSt8__detail15(void) __attribute__((weak)) {}
void _ZN7request8get_(void) __attribute__((weak)) {}
void fread(void) __attribute__((weak)) {}
void dlargv_(void) __attribute__((weak)) {}
void dscal_(void) __attribute__((weak)) {}
void dup2(void) __attribute__((weak)) {}
void MKL_Get_Max_Threads(void) __attribute__((weak)) {}
void ZGETRI(void) __attribute__((weak)) {}
void _ZNSt14basic_ifs(void) __attribute__((weak)) {}
void _ZNK7XMLNode15cr(void) __attribute__((weak)) {}
void _Z13get_localtimeP2tm(void) __attribute__((weak)) {}
void dnrm2_(void) __attribute__((weak)) {}
void _ZSt16__ostream_(void) __attribute__((weak)) {}
void fgetc(void) __attribute__((weak)) {}
void _Z12NewAclClientPSobb(void) __attribute__((weak)) {}
void dlarf_(void) __attribute__((weak)) {}
void _ZSt16__throw_ba(void) __attribute__((weak)) {}
void fgets(void) __attribute__((weak)) {}
void _ZN7request20Set(void) __attribute__((weak)) {}
void _ZN7request11acl(void) __attribute__((weak)) {}
void _ZN9ans_mutexC1Ev(void) __attribute__((weak)) {}
void exit(void) __attribute__((weak)) {}
void sin(void) __attribute__((weak)) {}
void dtrsm_(void) __attribute__((weak)) {}
void DORMQR(void) __attribute__((weak)) {}
void ffw_Open(void) __attribute__((weak)) {}
void __cxa_rethrow(void) __attribute__((weak)) {}
void sqrt(void) __attribute__((weak)) {}
void _ZSt19__throw_lo(void) __attribute__((weak)) {}
void _Z14unquote_stri(void) __attribute__((weak)) {}
void __cxa_pure_virtual(void) __attribute__((weak)) {}
void drotmg_(void) __attribute__((weak)) {}
void _Z19read_anslic_(void) __attribute__((weak)) {}
void time(void) __attribute__((weak)) {}
void qsort(void) __attribute__((weak)) {}
void ZPOTRF(void) __attribute__((weak)) {}
void gcvt(void) __attribute__((weak)) {}
void _ZNSo3putEc(void) __attribute__((weak)) {}
void cabs(void) __attribute__((weak)) {}
void abort(void) __attribute__((weak)) {}
void read(void) __attribute__((weak)) {}
void Tcl_NextHashEntry(void) __attribute__((weak)) {}
void _Z14get_anslic_d(void) __attribute__((weak)) {}
void _ZN7requestC1EPSo(void) __attribute__((weak)) {}
void atof(void) __attribute__((weak)) {}
void DGEEV(void) __attribute__((weak)) {}
void _ZNSi3getEPclc(void) __attribute__((weak)) {}
void _ZSt18_Rb_tree_d(void) __attribute__((weak)) {}
void kill(void) __attribute__((weak)) {}
void fputc(void) __attribute__((weak)) {}
void _ZN7request16Get(void) __attribute__((weak)) {}
void ZGEMM(void) __attribute__((weak)) {}
void _Z16string_makeu(void) __attribute__((weak)) {}
void MKL_Set_Num_Threads(void) __attribute__((weak)) {}
void fmod(void) __attribute__((weak)) {}
void dlarfg_(void) __attribute__((weak)) {}
void _Z19prddef_get_a(void) __attribute__((weak)) {}
void _Z21default_ansl(void) __attribute__((weak)) {}
void _Z8value_onNSt7_(void) __attribute__((weak)) {}
void _ZN13CAnsIdleSta(void) __attribute__((weak)) {}
void ddot_(void) __attribute__((weak)) {}
void rand(void) __attribute__((weak)) {}
void fork(void) __attribute__((weak)) {}
void floor(void) __attribute__((weak)) {}
void shmat(void) __attribute__((weak)) {}
void _exit(void) __attribute__((weak)) {}
void _ZN7request13Fre(void) __attribute__((weak)) {}
void _ZNSs4_Rep10_M_d(void) __attribute__((weak)) {}
void write(void) __attribute__((weak)) {}
void ctime(void) __attribute__((weak)) {}
void uncompress(void) __attribute__((weak)) {}
void expf(void) __attribute__((weak)) {}
void _Z13get_applogdi(void) __attribute__((weak)) {}
void puts(void) __attribute__((weak)) {}
void _ZNSs7reserveEm(void) __attribute__((weak)) {}
void _ZN7request21Set(void) __attribute__((weak)) {}
void DGEQRF(void) __attribute__((weak)) {}
void _ZSt24__throw_in(void) __attribute__((weak)) {}
void roundf(void) __attribute__((weak)) {}
void DGEQP3(void) __attribute__((weak)) {}
void _ZNSo5flushEv(void) __attribute__((weak)) {}
void _Z16read_environ(void) __attribute__((weak)) {}
void __cxa_end_catch(void) __attribute__((weak)) {}
void sincos(void) __attribute__((weak)) {}
void sleep(void) __attribute__((weak)) {}
void gzseek(void) __attribute__((weak)) {}
void _ZN7request26All(void) __attribute__((weak)) {}
void _ZNSsC1EPKcRKSaIcE(void) __attribute__((weak)) {}
void _Z16string_makel(void) __attribute__((weak)) {}
void _Z11delete_fileN(void) __attribute__((weak)) {}
void _ZN7request17set(void) __attribute__((weak)) {}
void sinh(void) __attribute__((weak)) {}
void __dynamic_cast(void) __attribute__((weak)) {}
void srand(void) __attribute__((weak)) {}
void __cxa_guard_release(void) __attribute__((weak)) {}
void gztell(void) __attribute__((weak)) {}
void chdir(void) __attribute__((weak)) {}
void _ZNSt12__basic_f(void) __attribute__((weak)) {}
void __gxx_personality_v0(void) __attribute__((weak)) {}
void ffw_CreateScope(void) __attribute__((weak)) {}
void _ZNSi3getEv(void) __attribute__((weak)) {}
unsigned char _ZTINSt8ios_base[1] __attribute__((weak)) = {0};
unsigned char _ZNSs4_Rep20_S_e[1] __attribute__((weak)) = {0};
unsigned char _ZTV16CAnsAcadem[1] __attribute__((weak)) = {0};
unsigned char _ZTISt8bad_cast[1] __attribute__((weak)) = {0};
unsigned char _ZTISt15basic_st[1] __attribute__((weak)) = {0};
unsigned char _ZTV14CAnsServerInfo[1] __attribute__((weak)) = {0};
unsigned char _ZTV16CAnsFeatur[1] __attribute__((weak)) = {0};
unsigned char _ZTVSi[1] __attribute__((weak)) = {0};
unsigned char _ZSt4cerr[1] __attribute__((weak)) = {0};

