/* Auto-generated global-symbol declarations (compile shims). */
#ifndef VSDLSS_GLOBALS_H
#define VSDLSS_GLOBALS_H


extern undefined8 DAT_00ab6798;   /* 8-byte global shim */
extern undefined8 DAT_00ab67b0;   /* 8-byte global shim */
extern undefined8 DAT_00ab71f0;   /* 8-byte global shim */
extern undefined8 DAT_00ab71f8;   /* 8-byte global shim */
extern undefined8 DAT_00ab7228;   /* 8-byte global shim */
extern undefined8 DAT_00ab7240;   /* 8-byte global shim */
extern undefined8 DAT_00ab7248;   /* 8-byte global shim */
extern undefined8 DAT_00ab7268;   /* 8-byte global shim */
extern undefined8 DAT_00ab72a0;   /* 8-byte global shim */
extern undefined8 DAT_00ab72f0;   /* 8-byte global shim */
extern undefined8 DAT_00ab841c;   /* 8-byte global shim */
extern undefined8 DAT_00aba108;   /* 8-byte global shim */
extern undefined8 DAT_00abc218;   /* 8-byte global shim */
extern undefined8 DAT_00abc248;   /* 8-byte global shim */
extern undefined8 DAT_00abc268;   /* 8-byte global shim */
extern undefined8 DAT_00abc298;   /* 8-byte global shim */
extern undefined8 DAT_00abcfec;   /* 8-byte global shim */
extern undefined8 DAT_00abcfef;   /* 8-byte global shim */
extern undefined8 DAT_00abd200;   /* 8-byte global shim */
extern undefined8 DAT_00ac53f8;   /* 8-byte global shim */
extern undefined8 DAT_00acae72;   /* 8-byte global shim */
extern undefined8 DAT_00acec78;   /* 8-byte global shim */
extern undefined8 DAT_00ad4f20;   /* 8-byte global shim */
extern undefined8 DAT_00af460a;   /* 8-byte global shim */
extern undefined8 DAT_00afab98;   /* 8-byte global shim */
extern undefined8 DAT_00b0eec8;   /* 8-byte global shim */
extern undefined8 DAT_00b11d60;   /* 8-byte global shim */
extern undefined8 DAT_00b126e8;   /* 8-byte global shim */
extern undefined8 DAT_00b185a6;   /* 8-byte global shim */
extern undefined8 DAT_00b18ef8;   /* 8-byte global shim */
extern undefined8 DAT_00b19051;   /* 8-byte global shim */
extern undefined8 DAT_00b190af;   /* 8-byte global shim */
extern undefined8 DAT_00b19720;   /* 8-byte global shim */
extern undefined8 DAT_00b1ab20;   /* 8-byte global shim */
extern undefined8 DAT_00b1c383;   /* 8-byte global shim */
extern undefined8 DAT_00b1d068;   /* 8-byte global shim */
extern undefined8 DAT_00b20e86;   /* 8-byte global shim */
extern undefined8 DAT_00b23b89;   /* 8-byte global shim */
extern undefined8 DAT_00b23e64;   /* 8-byte global shim */
extern undefined8 DAT_00b24458;   /* 8-byte global shim */
extern undefined8 DAT_00b24460;   /* 8-byte global shim */
extern undefined8 DAT_00e3bd34;   /* 8-byte global shim */
extern undefined8 DAT_00e3bd38;   /* 8-byte global shim */
extern undefined8 DAT_00e3bd3c;   /* 8-byte global shim */
extern undefined8 DAT_00e3bd40;   /* 8-byte global shim */
extern undefined8 DAT_00e3bd60;   /* 8-byte global shim */
extern undefined8 DAT_00e3be20;   /* 8-byte global shim */
extern undefined8 DAT_00e3be28;   /* 8-byte global shim */
extern undefined8 DAT_00e3c860;   /* 8-byte global shim */
extern undefined8 DAT_00e3c868;   /* 8-byte global shim */
extern undefined8 DAT_00e3c86c;   /* 8-byte global shim */
extern undefined8 DAT_00e3c870;   /* 8-byte global shim */
extern undefined8 DAT_00e3c878;   /* 8-byte global shim */
extern undefined8 DAT_00e3c880;   /* 8-byte global shim */
extern undefined8 DAT_00e3c88c;   /* 8-byte global shim */
extern undefined8 DAT_00e3c898;   /* 8-byte global shim */
extern undefined8 DAT_00e3d060;   /* 8-byte global shim */
extern undefined8 DAT_00e3d064;   /* 8-byte global shim */
extern undefined8 DAT_00e3d065;   /* 8-byte global shim */
extern undefined8 DAT_00e3d068;   /* 8-byte global shim */
extern undefined8 DAT_00e3d070;   /* 8-byte global shim */
extern undefined8 DAT_00e3d074;   /* 8-byte global shim */
extern undefined8 DAT_00e3d078;   /* 8-byte global shim */
extern undefined8 DAT_00e40660;   /* 8-byte global shim */
extern undefined8 DAT_00e413e8;   /* 8-byte global shim */
extern undefined8 DAT_00e96260;   /* 8-byte global shim */
extern undefined8 DAT_00e96340;   /* 8-byte global shim */
extern undefined8 DAT_00e96344;   /* 8-byte global shim */
extern undefined8 DAT_00e96440;   /* 8-byte global shim */
extern undefined8 DAT_00e96448;   /* 8-byte global shim */
extern undefined8 DAT_00e96460;   /* 8-byte global shim */
extern undefined8 DAT_00e96564;   /* 8-byte global shim */
extern undefined8 DAT_00e96568;   /* 8-byte global shim */
extern undefined8 DAT_00e9656c;   /* 8-byte global shim */
extern undefined8 DAT_00e96570;   /* 8-byte global shim */
extern undefined8 DAT_00e96590;   /* 8-byte global shim */
extern undefined8 DAT_00e96594;   /* 8-byte global shim */
extern undefined8 DAT_00e965a0;   /* 8-byte global shim */
extern undefined8 DAT_00e965a8;   /* 8-byte global shim */
extern undefined8 DAT_00e965b0;   /* 8-byte global shim */
extern undefined8 DAT_00eac1c8;   /* 8-byte global shim */
extern undefined8 DAT_00ead0a4;   /* 8-byte global shim */
extern undefined8 DAT_00ead1a4;   /* 8-byte global shim */
extern undefined8 DAT_00ead890;   /* 8-byte global shim */
extern undefined8 DAT_00ead898;   /* 8-byte global shim */
extern undefined8 DAT_00ead8a0;   /* 8-byte global shim */
extern undefined8 DAT_00ead8c0;   /* 8-byte global shim */
extern undefined8 DAT_00ead8e0;   /* 8-byte global shim */
extern undefined8 DAT_00ead908;   /* 8-byte global shim */
extern undefined8 DAT_00ead90c;   /* 8-byte global shim */
extern undefined8 DAT_00ead914;   /* 8-byte global shim */
extern undefined8 DAT_00ead920;   /* 8-byte global shim */
extern undefined8 DAT_00eada61;   /* 8-byte global shim */
extern undefined8 DAT_00eb19a0;   /* 8-byte global shim */
extern undefined8 DAT_00eb1aa8;   /* 8-byte global shim */
extern undefined8 DAT_00eb1ac0;   /* 8-byte global shim */
extern undefined8 DAT_00eb1ec4;   /* 8-byte global shim */
extern undefined8 DAT_00eb1ec8;   /* 8-byte global shim */
extern undefined8 DAT_00eb1ecc;   /* 8-byte global shim */
extern undefined8 DAT_00eb1ed0;   /* 8-byte global shim */
extern undefined8 DAT_00eb1ed8;   /* 8-byte global shim */
extern undefined8 DAT_00eb1ee0;   /* 8-byte global shim */
extern undefined8 DAT_00eb1ee8;   /* 8-byte global shim */
extern undefined8 DAT_00eb1ef0;   /* 8-byte global shim */
extern undefined8 DAT_00eb1ef8;   /* 8-byte global shim */
extern undefined8 DAT_00eb1f00;   /* 8-byte global shim */
extern undefined8 DAT_00eb1f04;   /* 8-byte global shim */
extern undefined8 DAT_00eb1f08;   /* 8-byte global shim */
extern undefined8 DAT_00eb1f10;   /* 8-byte global shim */
extern undefined8 DAT_00eb1f18;   /* 8-byte global shim */
extern undefined8 DAT_00eb1f20;   /* 8-byte global shim */
extern undefined8 DAT_00eb1f28;   /* 8-byte global shim */
extern undefined8 DAT_00eb1f30;   /* 8-byte global shim */
extern undefined8 DAT_00eb1f38;   /* 8-byte global shim */
extern undefined8 DAT_00eb1f40;   /* 8-byte global shim */
extern undefined8 DAT_00eb1f48;   /* 8-byte global shim */
extern undefined8 DAT_00ec4148;   /* 8-byte global shim */
extern undefined8 DAT_00ec4149;   /* 8-byte global shim */
extern undefined8 DAT_00ec4160;   /* 8-byte global shim */
extern undefined8 DAT_00ec4168;   /* 8-byte global shim */
extern undefined8 DAT_00ec4170;   /* 8-byte global shim */
extern undefined8 DAT_00ec4178;   /* 8-byte global shim */
extern undefined8 DAT_00ec4180;   /* 8-byte global shim */
extern undefined8 DAT_00ec4980;   /* 8-byte global shim */
extern undefined8 DAT_00ec4d80;   /* 8-byte global shim */
extern undefined8 DAT_00ec5180;   /* 8-byte global shim */
extern undefined8 DAT_00ec5980;   /* 8-byte global shim */
extern undefined8 DAT_00ec5d80;   /* 8-byte global shim */
extern undefined8 DAT_00ec5d88;   /* 8-byte global shim */
extern undefined8 DAT_00ec5d90;   /* 8-byte global shim */
extern undefined8 DAT_00ec5d98;   /* 8-byte global shim */
extern undefined8 DAT_00ec5da0;   /* 8-byte global shim */
extern undefined8 DAT_00ec5da8;   /* 8-byte global shim */
extern undefined8 DAT_00ec5db0;   /* 8-byte global shim */
extern undefined8 DAT_00ec5db4;   /* 8-byte global shim */
extern undefined8 DAT_00ec5db8;   /* 8-byte global shim */
extern undefined8 DAT_00ec5dbc;   /* 8-byte global shim */
extern undefined8 DAT_00ec5dc0;   /* 8-byte global shim */
extern undefined8 DAT_00ec5dc4;   /* 8-byte global shim */
extern undefined8 DAT_00ec5dc8;   /* 8-byte global shim */
extern undefined8 DAT_00ec5dd0;   /* 8-byte global shim */
extern undefined8 DAT_00ec5dd8;   /* 8-byte global shim */
extern undefined8 DAT_00ec5de0;   /* 8-byte global shim */
extern undefined8 DAT_00ec5de8;   /* 8-byte global shim */
extern undefined8 DAT_00ec5df0;   /* 8-byte global shim */
extern undefined8 DAT_00ec5df4;   /* 8-byte global shim */
extern undefined8 DAT_00ec5e58;   /* 8-byte global shim */
extern undefined8 DAT_00ec5e60;   /* 8-byte global shim */
extern undefined8 DAT_00ec5e7c;   /* 8-byte global shim */
extern undefined8 DAT_00ec5e80;   /* 8-byte global shim */
extern undefined8 DAT_00ec5e88;   /* 8-byte global shim */
extern undefined8 DAT_00ec5e90;   /* 8-byte global shim */
extern undefined8 DAT_00ec5e98;   /* 8-byte global shim */
extern undefined8 DAT_00ec5ea0;   /* 8-byte global shim */
extern undefined8 DAT_00ec5ea8;   /* 8-byte global shim */
extern undefined8 DAT_00ec5eb0;   /* 8-byte global shim */
extern undefined8 DAT_00ecb028;   /* 8-byte global shim */
extern undefined8 DAT_00ecb030;   /* 8-byte global shim */
extern undefined8 DAT_00ecb038;   /* 8-byte global shim */
extern undefined8 DAT_00ecb040;   /* 8-byte global shim */
extern undefined8 DAT_00ecb048;   /* 8-byte global shim */
extern undefined8 DAT_00ecb050;   /* 8-byte global shim */
extern undefined8 DAT_00ecb058;   /* 8-byte global shim */
extern undefined8 DAT_00ece210;   /* 8-byte global shim */
extern undefined8 DAT_00ece218;   /* 8-byte global shim */
extern undefined8 DAT_00ece220;   /* 8-byte global shim */
extern undefined8 DAT_00ece228;   /* 8-byte global shim */
extern undefined8 DAT_00ece230;   /* 8-byte global shim */
extern undefined8 DAT_00ece238;   /* 8-byte global shim */
extern undefined8 DAT_00ece240;   /* 8-byte global shim */
extern undefined8 DAT_00ece248;   /* 8-byte global shim */
extern undefined8 DAT_00f05ee0;   /* 8-byte global shim */
extern undefined8 DAT_00f061c0;   /* 8-byte global shim */
extern undefined8 DAT_00f07060;   /* 8-byte global shim */
extern undefined8 DAT_00f23920;   /* 8-byte global shim */
extern undefined8 DAT_00fa3920;   /* 8-byte global shim */
extern undefined8 INIT_ALLOC_MULT_vsdlss;   /* 8-byte global shim */
extern undefined8 MATRIX_CHANGED_vsdlss;   /* 8-byte global shim */
extern undefined8 NAME;   /* 8-byte global shim */
extern undefined8 NUMERICAL_ZERO_vsdlss;   /* 8-byte global shim */
extern undefined8 ONLY_MATRIX_VALUES_CHANGED;   /* 8-byte global shim */
extern undefined8 PRINT_STATS_vsdlss;   /* 8-byte global shim */
extern undefined8 PTR_DAT_00b23548;   /* 8-byte global shim */
extern undefined8 READ_BUFF_SIZE;   /* 8-byte global shim */
extern undefined8 SILENT_vsdlss;   /* 8-byte global shim */
extern undefined8 SINGLE_SOLVE_ONLY_vsdlss;   /* 8-byte global shim */
extern undefined8 ZeroPivot_VAL_vsdlss;   /* 8-byte global shim */
extern undefined8 _0_8_;   /* 8-byte global shim */
extern undefined8 _12_4_;   /* 8-byte global shim */
extern undefined8 _16_8_;   /* 8-byte global shim */
extern undefined8 _24_8_;   /* 8-byte global shim */
extern undefined8 _4_4_;   /* 8-byte global shim */
extern undefined8 _8_4_;   /* 8-byte global shim */
extern undefined8 _8_8_;   /* 8-byte global shim */
extern undefined8 _DAT_00ab67f8;   /* 8-byte global shim */
extern undefined8 _DAT_00b19718;   /* 8-byte global shim */
extern undefined8 _DAT_00b19728;   /* 8-byte global shim */
extern undefined8 _DAT_00b1a140;   /* 8-byte global shim */
extern undefined8 _DAT_00b1a158;   /* 8-byte global shim */
extern undefined8 _DAT_00b1ab28;   /* 8-byte global shim */
extern undefined8 _DAT_00b1ce38;   /* 8-byte global shim */
extern undefined8 _DAT_00b1ce40;   /* 8-byte global shim */
extern undefined8 _DAT_00b1d070;   /* 8-byte global shim */
extern undefined8 _DAT_00b1ddf8;   /* 8-byte global shim */
extern undefined8 _DAT_00b24350;   /* 8-byte global shim */
extern undefined8 _DAT_00e96240;   /* 8-byte global shim */
extern undefined8 _DAT_00e96598;   /* 8-byte global shim */
extern undefined8 _DAT_00ead888;   /* 8-byte global shim */
extern undefined8 _DAT_00ec5da0;   /* 8-byte global shim */
extern undefined8 _DAT_00ec5da8;   /* 8-byte global shim */
extern undefined8 _DAT_00ec5de8;   /* 8-byte global shim */
extern undefined8 appFreeFunPtr_vsdlss;   /* 8-byte global shim */
extern undefined8 appMallocFunPtr_vsdlss;   /* 8-byte global shim */
extern undefined8 availMem_vsdlss;   /* 8-byte global shim */
extern undefined8 avgChunkSize_vsdlss;   /* 8-byte global shim */
extern undefined8 baseJobName_vsdlss;   /* 8-byte global shim */
extern undefined8 blocksInProb_vsdlss;   /* 8-byte global shim */
extern undefined8 casiActivatePardisoF;   /* 8-byte global shim */
extern undefined8 casiParSolverF;   /* 8-byte global shim */
extern undefined8 chunksInProb_vsdlss;   /* 8-byte global shim */
extern undefined8 cmuChunkSizeRead;   /* 8-byte global shim */
extern undefined8 cmuChunkSizeWrite;   /* 8-byte global shim */
extern undefined8 cmuChunkedReadFNum;   /* 8-byte global shim */
extern undefined8 cmuChunkedReadFp;   /* 8-byte global shim */
extern undefined8 cmuChunkedWriteFNum;   /* 8-byte global shim */
extern undefined8 cmuChunkedWriteFp;   /* 8-byte global shim */
extern undefined8 cmuCurrentEntryRead;   /* 8-byte global shim */
extern undefined8 cmuCurrentEntryWrite;   /* 8-byte global shim */
extern undefined8 cmuFromNodeVecRead;   /* 8-byte global shim */
extern undefined8 cmuFromNodeVecWrite;   /* 8-byte global shim */
extern undefined8 cmuNumInCurrentChunk;   /* 8-byte global shim */
extern undefined8 cmuOffDiagVecRead;   /* 8-byte global shim */
extern undefined8 cmuOffDiagVecWrite;   /* 8-byte global shim */
extern undefined8 cmuToNodeVecRead;   /* 8-byte global shim */
extern undefined8 cmuToNodeVecWrite;   /* 8-byte global shim */
extern undefined8 copyrightLines_vsdlss;   /* 8-byte global shim */
extern undefined8 deg1NodesInProbOrig_vsdlss;   /* 8-byte global shim */
extern undefined8 deg2NodesInProbOrig_vsdlss;   /* 8-byte global shim */
extern undefined8 deg3NodesInProbOrig_vsdlss;   /* 8-byte global shim */
extern undefined8 dgemmOpCnt;   /* 8-byte global shim */
extern undefined8 elapsedFactorTime;   /* 8-byte global shim */
extern undefined8 elapsedLoadCaseSolveTime;   /* 8-byte global shim */
extern undefined8 elapsedPardisoFactorTime;   /* 8-byte global shim */
extern undefined8 elapsedPardisoLoadCaseSolveTime;   /* 8-byte global shim */
extern undefined8 elapsedPardisoReorderTime;   /* 8-byte global shim */
extern undefined8 elapsedPrePostProcTime;   /* 8-byte global shim */
extern undefined8 elapsedReducedSolveTime;   /* 8-byte global shim */
extern undefined8 elapsedReorderTime;   /* 8-byte global shim */
extern undefined8 elapsedTotalTime;   /* 8-byte global shim */
extern undefined8 elemsInProbOrig_vsdlss;   /* 8-byte global shim */
extern undefined8 elemsInProb_vsdlss;   /* 8-byte global shim */
extern undefined8 emtStatic_vsdlss;   /* 8-byte global shim */
extern undefined8 factorBlockMem_vsdlss;   /* 8-byte global shim */
extern undefined8 factorChunkMem_vsdlss;   /* 8-byte global shim */
extern undefined8 factorIndexSize_vsdlss;   /* 8-byte global shim */
extern undefined8 factorNZ_vsdlss;   /* 8-byte global shim */
extern undefined8 factorSize_vsdlss;   /* 8-byte global shim */
extern undefined8 factorValueSize_vsdlss;   /* 8-byte global shim */
extern undefined8 factorWithinBlockOpCnt;   /* 8-byte global shim */
extern undefined8 ftrwChunkSizeRead;   /* 8-byte global shim */
extern undefined8 ftrwChunkSizeWrite;   /* 8-byte global shim */
extern undefined8 ftrwCurrentEntryRead;   /* 8-byte global shim */
extern undefined8 ftrwCurrentEntryWrite;   /* 8-byte global shim */
extern undefined8 ftrwFromNodeVecRead;   /* 8-byte global shim */
extern undefined8 ftrwFromNodeVecWrite;   /* 8-byte global shim */
extern undefined8 ftrwNumItemsLeft;   /* 8-byte global shim */
extern undefined8 ftrwNumItemsWritten;   /* 8-byte global shim */
extern undefined8 ftrwOffDiagVecRead;   /* 8-byte global shim */
extern undefined8 ftrwOffDiagVecWrite;   /* 8-byte global shim */
extern undefined8 ftrwToNodeVecRead;   /* 8-byte global shim */
extern undefined8 ftrwToNodeVecWrite;   /* 8-byte global shim */
extern undefined8 inWorkerThreadsF;   /* 8-byte global shim */
extern undefined8 initOrderSelectedInProb_vsdlss;   /* 8-byte global shim */
extern undefined8 jobName_vsdlss;   /* 8-byte global shim */
extern undefined8 longVecsInFC;   /* 8-byte global shim */
extern undefined8 maxChunkSize_vsdlss;   /* 8-byte global shim */
extern undefined8 maxLevelInRCM_vsdlss;   /* 8-byte global shim */
extern undefined8 nodesInProbOrig_vsdlss;   /* 8-byte global shim */
extern undefined8 nodesInProb_vsdlss;   /* 8-byte global shim */
extern undefined8 numSeparatorsInProb_vsdlss;   /* 8-byte global shim */
extern undefined8 opsForTriangSolves_vsdlss;   /* 8-byte global shim */
extern undefined8 opsToFactor_vsdlss;   /* 8-byte global shim */
extern undefined8 overheadMem_vsdlss;   /* 8-byte global shim */
extern undefined8 pFVar1;   /* 8-byte global shim */
extern undefined8 pTVar1;   /* 8-byte global shim */
extern undefined8 pVar10;   /* 8-byte global shim */
extern undefined8 param_1;   /* 8-byte global shim */
extern undefined8 ppuVar10;   /* 8-byte global shim */
extern undefined8 propStaticMsg_vsdlss;   /* 8-byte global shim */
extern undefined8 s;   /* 8-byte global shim */
extern undefined8 s_Solver_vsdlss_failed_with_status_00b21b38;   /* 8-byte global shim */
extern undefined8 s_Solver_vsdlss_failed_with_status_00b25100;   /* 8-byte global shim */
extern undefined8 s_Solver_vsdlss_returned_successfu_00b21b60;   /* 8-byte global shim */
extern undefined8 s_VSDLSS_jobName_exceeds_buffer_le_00b17460;   /* 8-byte global shim */
extern undefined8 s_Version__s_vsdlss_s_Source_File__00b239a0;   /* 8-byte global shim */
extern undefined8 s___UWRAPPER_1_9_for_VSDLSS_HMSLSS_00b1e458;   /* 8-byte global shim */
extern undefined8 s___VSDLSS_4_4__Very_Sparse_Direct_00b19298;   /* 8-byte global shim */
extern undefined8 s____________Starting_vsdlss1mem___00b19c90;   /* 8-byte global shim */
extern undefined8 s____________vsdlss1_ended_with__d_00b24110;   /* 8-byte global shim */
extern undefined8 s____________vsdlss1_ended_with__l_00b19858;   /* 8-byte global shim */
extern undefined8 s____________vsdlss1mem_ended_with_00b19e18;   /* 8-byte global shim */
extern undefined8 s____________vsdlss1mem_ended_with_00b23fc8;   /* 8-byte global shim */
extern undefined8 s_______vsdlss_Error_______00b238a6;   /* 8-byte global shim */
extern undefined8 s_______vsdlss_Warning_______00b2388a;   /* 8-byte global shim */
extern undefined8 s_vsdlss1_c_00b198d2;   /* 8-byte global shim */
extern undefined8 s_vsdlss1mem_c_00b19b7e;   /* 8-byte global shim */
extern undefined8 s_vsdlss1memutils_c_00b19e55;   /* 8-byte global shim */
extern undefined8 s_vsdlss_00abcfe5;   /* 8-byte global shim */
extern undefined8 s_vsdlss_FATAL_00b18644;   /* 8-byte global shim */
extern undefined8 s_vsdlss_c_00b19030;   /* 8-byte global shim */
extern undefined8 s_vsdlss_s_00b2386c;   /* 8-byte global shim */
extern undefined8 s_vsdlss_s__00b22b21;   /* 8-byte global shim */
extern undefined8 solver_mbytes;   /* 8-byte global shim */
extern undefined8 stack0x00000008;   /* 8-byte global shim */
extern undefined8 t_dgemm;   /* 8-byte global shim */
extern undefined8 t_divideIntoChunks_vsdlss;   /* 8-byte global shim */
extern undefined8 t_factorIO_vsdlss;   /* 8-byte global shim */
extern undefined8 t_factorKernel_vsdlss;   /* 8-byte global shim */
extern undefined8 t_factorWithinBlock_vsdlss;   /* 8-byte global shim */
extern undefined8 t_factor_vsdlss;   /* 8-byte global shim */
extern undefined8 t_lowerSolveIO_vsdlss;   /* 8-byte global shim */
extern undefined8 t_lowerSolve_vsdlss;   /* 8-byte global shim */
extern undefined8 t_minDegree_vsdlss;   /* 8-byte global shim */
extern undefined8 t_permuteA_vsdlss;   /* 8-byte global shim */
extern undefined8 t_prepostproc_vsdlss;   /* 8-byte global shim */
extern undefined8 t_reducedSolve_vsdlss;   /* 8-byte global shim */
extern undefined8 t_reorder_vsdlss;   /* 8-byte global shim */
extern undefined8 t_subBlockContribFromRowRange;   /* 8-byte global shim */
extern undefined8 t_symElim_vsdlss;   /* 8-byte global shim */
extern undefined8 t_upperSolveIO_vsdlss;   /* 8-byte global shim */
extern undefined8 t_upperSolve_vsdlss;   /* 8-byte global shim */
extern undefined8 t_work1_vsdlss;   /* 8-byte global shim */
extern undefined8 t_work2_vsdlss;   /* 8-byte global shim */
extern undefined8 t_work3_vsdlss;   /* 8-byte global shim */
extern undefined8 t_work4;   /* 8-byte global shim */
extern undefined8 t_work5;   /* 8-byte global shim */
extern undefined8 this;   /* 8-byte global shim */
extern undefined8 upperANZ_vsdlss;   /* 8-byte global shim */
extern undefined8 use_casi64bit_solver;   /* 8-byte global shim */
extern undefined8 varsInProbOrig_vsdlss;   /* 8-byte global shim */
extern undefined8 varsInProb_vsdlss;   /* 8-byte global shim */
extern undefined8 vsdlssEnv_vsdlss;   /* 8-byte global shim */
extern undefined8 vsdlssMessage_vsdlss;   /* 8-byte global shim */
extern undefined8 vsdlssStatus_vsdlss;   /* 8-byte global shim */
extern undefined8 vsdlssThreadEnv;   /* 8-byte global shim */
extern undefined8 vsdlssThreadStatus;   /* 8-byte global shim */

#endif
