"""Generate explicit width 1..6 triangular kernels; retain scalar operation order."""
from pathlib import Path
out=['/* Generated by tools/generate_small_solve.py; do not edit by hand. */']
for w in range(1,7):
 out += [f'static vsdlss_status solve_{w}(const double *a,csi b,csi ext,const csi *idx,double *x,int back) {{',f' csi rows={w}+ext; double d,v;', ' if(!back) {']
 for j in range(w):
  out += [f' d=a[{j}*rows+{j}]; if(!isfinite(d)||d<=0)return VSDLSS_ERR_INVALID;',f' x[b+{j}]/=d; if(!isfinite(x[b+{j}]))return VSDLSS_ERR_NONFINITE;']
  for r in range(j+1,w):out += [f' x[b+{r}]-=a[{j}*rows+{r}]*x[b+{j}];']
 out += [' int bad=0; for(csi r=0;r<ext;r++) { v=x[idx[r]];']
 for j in range(w):out += [f' v-=a[{j}*rows+{w}+r]*x[b+{j}];']
 out += [' x[idx[r]]=v; if(!isfinite(v))bad=1; }',' if(bad)return VSDLSS_ERR_NONFINITE;',' } else {',' int bad=0;']
 # One pass over the external rows: x[idx[r]] is read once and the w
 # column sums advance as independent chains, each in ascending r (the
 # same operations as one loop per column).
 out += [' ' + ' '.join(f'double v{j}=x[b+{j}];' for j in range(w)),
         ' for(csi r=0;r<ext;r++) { const double xr=x[idx[r]];']
 for j in range(w):out += [f' v{j}-=a[{j}*rows+{w}+r]*xr;']
 out += [' }']
 for j in range(w):out += [f' x[b+{j}]=v{j}; if(!isfinite(v{j}))bad=1;']
 out += [' if(bad)return VSDLSS_ERR_NONFINITE;']
 for j in reversed(range(w)):
  out += [f' d=a[{j}*rows+{j}]; v=x[b+{j}]; if(!isfinite(d)||d<=0)return VSDLSS_ERR_INVALID;']
  for r in range(j+1,w):out += [f' v-=a[{j}*rows+{r}]*x[b+{r}];']
  out += [f' x[b+{j}]=v/d; if(!isfinite(x[b+{j}]))return VSDLSS_ERR_NONFINITE;']
 out += [' } return VSDLSS_OK;','}']
Path(__file__).resolve().parents[1].joinpath('src/vsdlss_small_solve.inc').write_text('\n'.join(out)+'\n')
